[project]
name = "automations"
version = "0.1.0"
description = "Project encompassing various automation scripts."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "jarvis",
    "core",
    "scrapers",
    "dashboards",
]

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "B",
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = [
    "core",
    "dashboards",
    "jarvis",
    "scrapers",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
